// <auto-generated />
using System;
using APIQuyenGop.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIQuyenGop.Migrations
{
    [DbContext(typeof(QuyNguyenGopFPOLYContext))]
    partial class QuyNguyenGopFPOLYContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("APIQuyenGop.Models.TbBaiVietChuongTrinhNguyenGop", b =>
                {
                    b.Property<int>("IdBaiViet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBaiViet"), 1L, 1);

                    b.Property<string>("CauChuyen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoanCanh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdCcng")
                        .HasColumnType("int");

                    b.Property<int?>("IdChuDe")
                        .HasColumnType("int");

                    b.Property<string>("TacGia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ThoiGianDangBaiViet")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdBaiViet");

                    b.ToTable("TbBaiVietChuongTrinhNguyenGop");
                });

            modelBuilder.Entity("APIQuyenGop.Models.TbChuDe", b =>
                {
                    b.Property<int>("IdChuDe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdChuDe"), 1L, 1);

                    b.Property<string>("TenChuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdChuDe");

                    b.ToTable("TbChuDe");
                });

            modelBuilder.Entity("APIQuyenGop.Models.TbChuongTrinhNguyenGop", b =>
                {
                    b.Property<int>("IdCcng")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCcng"), 1L, 1);

                    b.Property<string>("DiaDiemNguyenGop")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhThucNguyenGop")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdNng")
                        .HasColumnType("int");

                    b.Property<int?>("IdToChuc")
                        .HasColumnType("int");

                    b.Property<int>("LuotNguyenGop")
                        .HasColumnType("int");

                    b.Property<string>("MucDichNguyenGop")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoTienCanNguyenGop")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaiKhoanNguyenGop")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenChuongTrinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCcng");

                    b.ToTable("TbChuongTrinhNguyenGop");
                });

            modelBuilder.Entity("APIQuyenGop.Models.TbNguoiNguyenGop", b =>
                {
                    b.Property<int>("IdNng")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNng"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhThucNguyenGop")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoVaTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LienHe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MucDichNguyenGop")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayNguyenGop")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoTienNguyenGop")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdNng");

                    b.ToTable("TbNguoiNguyenGop");
                });

            modelBuilder.Entity("APIQuyenGop.Models.TbToChucDongHanh", b =>
                {
                    b.Property<int>("IdToChuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdToChuc"), 1L, 1);

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenToChuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdToChuc");

                    b.ToTable("TbToChucDongHanh");
                });
#pragma warning restore 612, 618
        }
    }
}
